# Generated by Django 3.2.8 on 2021-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(),
        ),
    ]
